"""
==============================================================================
Ghana FDA & WHO West Africa Essential Medicines Formulary Seeder
==============================================================================
Statutory master catalog of 65+ essential pharmaceutical molecules with
Act 857 Poison Schedules, cold-chain temperature thresholds, standard dosing
guidelines, and linked ICD-10 diagnostic indications.
"""

import logging
from typing import Any, Dict, List
import uuid

from sqlalchemy import or_
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.models.inventory import GlobalMedication


logger = logging.getLogger("medipaedia.db.formulary")

GHANA_FDA_WHO_ESSENTIAL_FORMULARY: List[Dict[str, Any]] = [
    # --------------------------------------------------------------------------
    # 1. ANTIMALARIALS (ACT & SEVERE REGIMENS)
    # --------------------------------------------------------------------------
    {
        "generic_name": "Artemether + Lumefantrine",
        "brand_name": "Coartem / Artefan",
        "dosage_form": "Tablet",
        "strength": "20mg/120mg",
        "category": "Antimalarial (ACT)",
        "therapeutic_class": "Artemisinin-based Combination Therapy",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "4 tablets stat, then 4 tablets at 8h, 24h, 36h, 48h, 60h with fatty meal",
        "is_cold_chain": False,
        "linked_icd10_codes": "B50.9,B54",
        "nafdac_fda_number": "FDA/SD.24-0012",
        "description": "First-line ACT for uncomplicated Plasmodium falciparum malaria in Ghana & West Africa.",
    },
    {
        "generic_name": "Artesunate",
        "brand_name": "Artesun IV",
        "dosage_form": "Powder for Injection",
        "strength": "60mg/Vial",
        "category": "Antimalarial (Severe)",
        "therapeutic_class": "Artemisinin Derivative",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "2.4 mg/kg IV stat at 0h, 12h, 24h, then once daily until oral switch",
        "is_cold_chain": False,
        "linked_icd10_codes": "B50.0,B50.8,B50.9",
        "nafdac_fda_number": "FDA/SD.24-0013",
        "description": "Gold-standard parenteral treatment for severe, cerebral, and complicated falciparum malaria.",
    },
    {
        "generic_name": "Dihydroartemisinin + Piperaquine",
        "brand_name": "P-Alaxin / Duocotecxin",
        "dosage_form": "Tablet",
        "strength": "40mg/320mg",
        "category": "Antimalarial (ACT)",
        "therapeutic_class": "Artemisinin-based Combination Therapy",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "3 tablets once daily for 3 consecutive days taken with water",
        "is_cold_chain": False,
        "linked_icd10_codes": "B50.9",
        "nafdac_fda_number": "FDA/SD.24-0014",
        "description": "Second-line Artemisinin combination therapy with prolonged post-treatment prophylactic tail.",
    },
    {
        "generic_name": "Sulfadoxine + Pyrimethamine",
        "brand_name": "Fansidar / Maloxine",
        "dosage_form": "Tablet",
        "strength": "500mg/25mg",
        "category": "Antimalarial (IPTp)",
        "therapeutic_class": "Antifolate Antimalarial",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "3 tablets stat as Directly Observed Therapy (DOT) at monthly ANC visits from 16 weeks",
        "is_cold_chain": False,
        "linked_icd10_codes": "Z34.8,B50.9",
        "nafdac_fda_number": "FDA/SD.24-0015",
        "description": "Intermittent Preventive Treatment in Pregnancy (IPTp-SP) for gestational malaria prevention.",
    },
    {
        "generic_name": "Quinine Dihydrochloride",
        "brand_name": "Quinine Injection",
        "dosage_form": "Injection",
        "strength": "300mg/ml (2ml Ampoule)",
        "category": "Antimalarial (Cinchona)",
        "therapeutic_class": "Cinchona Alkaloid",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "Loading dose 20 mg/kg in 5% dextrose over 4h, then 10 mg/kg 8-hourly",
        "is_cold_chain": False,
        "linked_icd10_codes": "B50.0,B50.9",
        "nafdac_fda_number": "FDA/SD.24-0016",
        "description": "Alternative parenteral antimalarial for severe malaria and first-trimester gestational malaria.",
    },
    {
        "generic_name": "Artemether + Lumefantrine Dispersible",
        "brand_name": "Coartem Dispersible",
        "dosage_form": "Dispersible Tablet",
        "strength": "20mg/120mg",
        "category": "Antimalarial (Pediatric)",
        "therapeutic_class": "Pediatric Artemisinin-based Combination Therapy",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "1 to 3 tabs dispersible in water based on weight band at 0h, 8h, 24h, 36h, 48h, 60h",
        "is_cold_chain": False,
        "linked_icd10_codes": "B50.9",
        "nafdac_fda_number": "FDA/SD.24-0017",
        "description": "Pediatric sweet-flavored dispersible ACT for infants and children 5kg-35kg.",
    },

    # --------------------------------------------------------------------------
    # 2. ANTIBIOTICS & ANTIMICROBIALS
    # --------------------------------------------------------------------------
    {
        "generic_name": "Amoxicillin + Clavulanic Acid",
        "brand_name": "Augmentin / AmoxClav",
        "dosage_form": "Tablet",
        "strength": "625mg",
        "category": "Broad-Spectrum Antibiotic",
        "therapeutic_class": "Beta-Lactam + Beta-Lactamase Inhibitor",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "625mg PO 8-hourly (TDS) or 1g 12-hourly for 5 to 7 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "J01.9,J06.9,J18.9,L03.9",
        "nafdac_fda_number": "FDA/SD.24-0045",
        "description": "Beta-lactam for community-acquired pneumonia, sinusitis, otitis media, and skin infections.",
    },
    {
        "generic_name": "Amoxicillin",
        "brand_name": "Amoxil / Amox-Denk",
        "dosage_form": "Capsule",
        "strength": "500mg",
        "category": "Aminopenicillin Antibiotic",
        "therapeutic_class": "Broad-Spectrum Aminopenicillin",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "500mg PO 8-hourly (TDS) for 5 to 7 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "J02.9,J03.9,J18.9",
        "nafdac_fda_number": "FDA/SD.24-0044",
        "description": "First-line oral penicillin for streptococcal pharyngitis, acute otitis media, and dental infections.",
    },
    {
        "generic_name": "Ceftriaxone Sodium",
        "brand_name": "Rocephin / Ceftriaxone",
        "dosage_form": "Powder for Injection",
        "strength": "1g/Vial",
        "category": "Cephalosporin Antibiotic",
        "therapeutic_class": "Third-Generation Cephalosporin",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "1g to 2g IV/IM once daily (OD) for 5 to 10 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "A01.0,G00.9,A41.9,N39.0",
        "nafdac_fda_number": "FDA/SD.24-0046",
        "description": "Hospital workhorse cephalosporin for bacterial meningitis, enteric fever, and severe sepsis.",
    },
    {
        "generic_name": "Ciprofloxacin Hydrochloride",
        "brand_name": "Cipro / Cipro-Denk",
        "dosage_form": "Tablet",
        "strength": "500mg",
        "category": "Fluoroquinolone Antibiotic",
        "therapeutic_class": "Fluoroquinolone",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "500mg PO 12-hourly (BD) for 7 to 14 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "A01.0,A09,N39.0,K65.0",
        "nafdac_fda_number": "FDA/SD.24-0102",
        "description": "Broad-spectrum coverage for Salmonella typhi (enteric fever), complicated cystitis, and pyelonephritis.",
    },
    {
        "generic_name": "Azithromycin",
        "brand_name": "Zithromax",
        "dosage_form": "Tablet",
        "strength": "500mg",
        "category": "Macrolide Antibiotic",
        "therapeutic_class": "Azalide / Macrolide",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "500mg PO once daily for 3 days or 500mg stat then 250mg OD x 4 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "J18.9,A54.9,A56.0,J02.9",
        "nafdac_fda_number": "FDA/SD.24-0210",
        "description": "Indicated for atypical respiratory tract infections, chlamydia, and gonococcal co-infections.",
    },
    {
        "generic_name": "Metronidazole",
        "brand_name": "Flagyl",
        "dosage_form": "Tablet",
        "strength": "400mg",
        "category": "Antiprotozoal & Anaerobic Antibiotic",
        "therapeutic_class": "Nitroimidazole",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "400mg PO 8-hourly (TDS) with meals for 5 to 7 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "A06.0,A07.1,N76.0,K65.0",
        "nafdac_fda_number": "FDA/SD.24-0047",
        "description": "First-line for amoebiasis, giardiasis, trichomoniasis, and intra-abdominal anaerobic infections.",
    },
    {
        "generic_name": "Metronidazole Infusion",
        "brand_name": "Flagyl IV",
        "dosage_form": "IV Infusion",
        "strength": "500mg/100ml",
        "category": "Antiprotozoal & Anaerobic Antibiotic",
        "therapeutic_class": "Nitroimidazole",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "500mg IV 8-hourly infused over 30 minutes",
        "is_cold_chain": False,
        "linked_icd10_codes": "K35.8,K65.0,N73.9",
        "nafdac_fda_number": "FDA/SD.24-0048",
        "description": "Surgical prophylaxis and treatment of deep pelvic and intra-abdominal anaerobic sepsis.",
    },
    {
        "generic_name": "Ampicillin Sodium",
        "brand_name": "Ampicillin IV/IM",
        "dosage_form": "Powder for Injection",
        "strength": "500mg/Vial",
        "category": "Penicillin Antibiotic",
        "therapeutic_class": "Aminopenicillin",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "500mg to 1g IV/IM 6-hourly",
        "is_cold_chain": False,
        "linked_icd10_codes": "P36.9,A40.9,J18.9",
        "nafdac_fda_number": "FDA/SD.24-0049",
        "description": "Essential neonatal antibiotic for suspected early-onset sepsis and Listeria meningitis.",
    },
    {
        "generic_name": "Cefuroxime Axetil",
        "brand_name": "Zinnat",
        "dosage_form": "Tablet",
        "strength": "500mg",
        "category": "Cephalosporin Antibiotic",
        "therapeutic_class": "Second-Generation Cephalosporin",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "500mg PO 12-hourly (BD) with food for 7 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "J01.9,J18.9,N39.0",
        "nafdac_fda_number": "FDA/SD.24-0050",
        "description": "Oral cephalosporin for step-down therapy in lower respiratory infections and pyelonephritis.",
    },
    {
        "generic_name": "Gentamicin Sulphate",
        "brand_name": "Gentamicin Injection",
        "dosage_form": "Injection",
        "strength": "80mg/2ml Ampoule",
        "category": "Aminoglycoside Antibiotic",
        "therapeutic_class": "Aminoglycoside",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "5 mg/kg IV once daily (OD) with serum creatinine monitoring",
        "is_cold_chain": False,
        "linked_icd10_codes": "P36.9,A41.9,N30.0",
        "nafdac_fda_number": "FDA/SD.24-0051",
        "description": "Potent Gram-negative bactericidal for neonatal sepsis, endocarditis, and pyelonephritis.",
    },
    {
        "generic_name": "Doxycycline Hyclate",
        "brand_name": "Doxy-Denk / Vibramycin",
        "dosage_form": "Capsule",
        "strength": "100mg",
        "category": "Tetracycline Antibiotic",
        "therapeutic_class": "Tetracycline",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "100mg PO 12-hourly on Day 1, then 100mg once daily with full glass of water",
        "is_cold_chain": False,
        "linked_icd10_codes": "A00.9,A56.0,A79.9,L70.0",
        "nafdac_fda_number": "FDA/SD.24-0052",
        "description": "First-line for cholera, chlamydia, rickettsial tick-borne typhus, and acne vulgaris.",
    },
    {
        "generic_name": "Nitrofurantoin",
        "brand_name": "Macrobid / Macrodantin",
        "dosage_form": "Capsule",
        "strength": "100mg",
        "category": "Urinary Antibacterial",
        "therapeutic_class": "Nitrofuran",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "100mg PO 12-hourly (BD) with food for 5 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "N30.0,N39.0",
        "nafdac_fda_number": "FDA/SD.24-0053",
        "description": "First-line empirical treatment for uncomplicated acute cystitis in females.",
    },
    {
        "generic_name": "Cotrimoxazole (Trimethoprim + Sulfamethoxazole)",
        "brand_name": "Septrin / Bactrim",
        "dosage_form": "Tablet",
        "strength": "480mg (80mg/400mg)",
        "category": "Sulfonamide Antibacterial",
        "therapeutic_class": "Folate Synthesis Inhibitor",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "960mg (2 tabs) PO 12-hourly (BD) for 7 days or 1 tab daily for HIV prophylaxis",
        "is_cold_chain": False,
        "linked_icd10_codes": "B20,B59,N39.0,J18.9",
        "nafdac_fda_number": "FDA/SD.24-0054",
        "description": "Pneumocystis jirovecii prophylaxis in immunocompromised patients and UTI therapy.",
    },
    {
        "generic_name": "Cloxacillin Sodium",
        "brand_name": "Cloxacillin Capsules",
        "dosage_form": "Capsule",
        "strength": "500mg",
        "category": "Antistaphylococcal Penicillin",
        "therapeutic_class": "Penicillinase-Resistant Penicillin",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "500mg PO 6-hourly (QDS) 1 hour before meals for 7 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "L01.0,L02.9,L03.9,M86.9",
        "nafdac_fda_number": "FDA/SD.24-0055",
        "description": "Targeted therapy for MSSA skin boils, impetigo, cellulitis, and staphylococcal osteomyelitis.",
    },
    {
        "generic_name": "Benzathine Penicillin G",
        "brand_name": "Penadur / Benzathine Pen",
        "dosage_form": "Powder for Injection",
        "strength": "2.4 MIU/Vial",
        "category": "Repository Penicillin",
        "therapeutic_class": "Long-Acting Beta-Lactam",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "2.4 MIU deep IM stat as single dose or weekly x 3 weeks for latent syphilis",
        "is_cold_chain": False,
        "linked_icd10_codes": "A51.0,A52.9,I00",
        "nafdac_fda_number": "FDA/SD.24-0056",
        "description": "Primary therapy for syphilis and secondary prophylaxis of rheumatic fever.",
    },
    {
        "generic_name": "Erythromycin Stearate",
        "brand_name": "Erythrocin",
        "dosage_form": "Tablet",
        "strength": "500mg",
        "category": "Macrolide Antibiotic",
        "therapeutic_class": "Macrolide",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "500mg PO 6-hourly (QDS) before meals for 7 to 10 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "J02.9,A36.9,A37.9",
        "nafdac_fda_number": "FDA/SD.24-0058",
        "description": "Alternative antibiotic for penicillin-allergic patients and Bordetella pertussis treatment.",
    },
    {
        "generic_name": "Fluconazole",
        "brand_name": "Diflucan",
        "dosage_form": "Capsule",
        "strength": "150mg",
        "category": "Antifungal",
        "therapeutic_class": "Triazole Antifungal",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "150mg PO stat for vaginal candidiasis or 200mg OD for systemic fungal infection",
        "is_cold_chain": False,
        "linked_icd10_codes": "B37.0,B37.3,B45.9",
        "nafdac_fda_number": "FDA/SD.24-0057",
        "description": "First-line oral antifungal for mucosal candidiasis and cryptococcal meningitis maintenance.",
    },

    # --------------------------------------------------------------------------
    # 3. CARDIOVASCULAR & METABOLIC FORMULARY
    # --------------------------------------------------------------------------
    {
        "generic_name": "Amlodipine Besylate",
        "brand_name": "Norvasc / Amlod",
        "dosage_form": "Tablet",
        "strength": "10mg",
        "category": "Antihypertensive",
        "therapeutic_class": "Calcium Channel Blocker (Dihydropyridine)",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "5mg to 10mg PO once daily (OD) morning",
        "is_cold_chain": False,
        "linked_icd10_codes": "I10,I11.9,I20.9",
        "nafdac_fda_number": "FDA/SD.24-0156",
        "description": "Dihydropyridine CCB; first-line therapy for essential hypertension in black African populations.",
    },
    {
        "generic_name": "Losartan Potassium",
        "brand_name": "Cozaar",
        "dosage_form": "Tablet",
        "strength": "50mg",
        "category": "Antihypertensive",
        "therapeutic_class": "Angiotensin II Receptor Blocker (ARB)",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "50mg to 100mg PO once daily (OD)",
        "is_cold_chain": False,
        "linked_icd10_codes": "I10,E11.9,N18.9",
        "nafdac_fda_number": "FDA/SD.24-0234",
        "description": "ARB for hypertension with renal protection in diabetic nephropathy without ACEI cough.",
    },
    {
        "generic_name": "Lisinopril",
        "brand_name": "Zestril / Lisodur",
        "dosage_form": "Tablet",
        "strength": "10mg",
        "category": "Antihypertensive",
        "therapeutic_class": "ACE Inhibitor",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "10mg to 20mg PO once daily (OD) with serum potassium monitoring",
        "is_cold_chain": False,
        "linked_icd10_codes": "I10,I50.9,I21.9",
        "nafdac_fda_number": "FDA/SD.24-0157",
        "description": "ACE inhibitor indicated for hypertension, congestive heart failure, and post-myocardial infarction.",
    },
    {
        "generic_name": "Hydrochlorothiazide (HCTZ)",
        "brand_name": "Esidrex / HCTZ",
        "dosage_form": "Tablet",
        "strength": "25mg",
        "category": "Diuretic & Antihypertensive",
        "therapeutic_class": "Thiazide Diuretic",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "12.5mg to 25mg PO once daily in the morning",
        "is_cold_chain": False,
        "linked_icd10_codes": "I10,I50.9",
        "nafdac_fda_number": "FDA/SD.24-0158",
        "description": "Thiazide diuretic; cornerstone first-line combination therapy for essential hypertension.",
    },
    {
        "generic_name": "Atenolol",
        "brand_name": "Tenormin",
        "dosage_form": "Tablet",
        "strength": "50mg",
        "category": "Antihypertensive & Antiarrhythmic",
        "therapeutic_class": "Cardioselective Beta-1 Blocker",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "50mg to 100mg PO once daily",
        "is_cold_chain": False,
        "linked_icd10_codes": "I10,I20.9,I48.9",
        "nafdac_fda_number": "FDA/SD.24-0159",
        "description": "Beta-blocker for rate control in atrial fibrillation, chronic angina, and essential tremor.",
    },
    {
        "generic_name": "Bisoprolol Fumarate",
        "brand_name": "Concor",
        "dosage_form": "Tablet",
        "strength": "5mg",
        "category": "Cardiovascular (Heart Failure)",
        "therapeutic_class": "Cardioselective Beta-Blocker",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "1.25mg initial titration up to 10mg PO once daily for heart failure",
        "is_cold_chain": False,
        "linked_icd10_codes": "I50.9,I10",
        "nafdac_fda_number": "FDA/SD.24-0160",
        "description": "Guideline-directed medical therapy for chronic heart failure with reduced ejection fraction (HFrEF).",
    },
    {
        "generic_name": "Atorvastatin Calcium",
        "brand_name": "Lipitor / Atorva",
        "dosage_form": "Tablet",
        "strength": "20mg",
        "category": "Lipid-Lowering Agent",
        "therapeutic_class": "HMG-CoA Reductase Inhibitor (Statin)",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "20mg to 40mg PO once daily at bedtime",
        "is_cold_chain": False,
        "linked_icd10_codes": "E78.0,I25.1,I63.9",
        "nafdac_fda_number": "FDA/SD.24-0161",
        "description": "High-intensity statin for primary and secondary cardiovascular risk reduction and hypercholesterolemia.",
    },
    {
        "generic_name": "Rosuvastatin Calcium",
        "brand_name": "Crestor",
        "dosage_form": "Tablet",
        "strength": "10mg",
        "category": "Lipid-Lowering Agent",
        "therapeutic_class": "HMG-CoA Reductase Inhibitor",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "10mg to 20mg PO once daily evening",
        "is_cold_chain": False,
        "linked_icd10_codes": "E78.0,I25.1",
        "nafdac_fda_number": "FDA/SD.24-0167",
        "description": "Potent hydrophilic statin for severe familial hypercholesterolemia and atherosclerotic plaque stabilization.",
    },
    {
        "generic_name": "Metformin Hydrochloride",
        "brand_name": "Glucophage",
        "dosage_form": "Tablet",
        "strength": "500mg",
        "category": "Oral Antidiabetic",
        "therapeutic_class": "Biguanide",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "500mg PO 12-hourly with meals, titrating to 1g BD as tolerated",
        "is_cold_chain": False,
        "linked_icd10_codes": "E11.9,E66.9",
        "nafdac_fda_number": "FDA/SD.24-0125",
        "description": "First-line oral pharmacotherapy for Type 2 Diabetes Mellitus management and insulin resistance.",
    },
    {
        "generic_name": "Glibenclamide",
        "brand_name": "Daonil",
        "dosage_form": "Tablet",
        "strength": "5mg",
        "category": "Oral Antidiabetic",
        "therapeutic_class": "Sulfonylurea",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "2.5mg to 5mg PO once daily with breakfast",
        "is_cold_chain": False,
        "linked_icd10_codes": "E11.9",
        "nafdac_fda_number": "FDA/SD.24-0126",
        "description": "Second-generation sulfonylurea insulin secretagogue for Type 2 diabetes glycemic control.",
    },
    {
        "generic_name": "Furosemide",
        "brand_name": "Lasix / Furosemide",
        "dosage_form": "Tablet",
        "strength": "40mg",
        "category": "Loop Diuretic",
        "therapeutic_class": "Loop Diuretic",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "40mg PO once or twice daily morning/afternoon",
        "is_cold_chain": False,
        "linked_icd10_codes": "I50.9,N04.9,R60.9",
        "nafdac_fda_number": "FDA/SD.24-0162",
        "description": "Potent loop diuretic for pulmonary edema, congestive heart failure fluid overload, and renal ascites.",
    },
    {
        "generic_name": "Furosemide Injection",
        "brand_name": "Lasix IV",
        "dosage_form": "Injection",
        "strength": "20mg/2ml Ampoule",
        "category": "Loop Diuretic",
        "therapeutic_class": "Loop Diuretic",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "20mg to 80mg slow IV bolus for acute decompensated heart failure",
        "is_cold_chain": False,
        "linked_icd10_codes": "I50.9,J81.0",
        "nafdac_fda_number": "FDA/SD.24-0163",
        "description": "Emergency IV diuretic for acute acute pulmonary edema and severe hypertensive crisis.",
    },
    {
        "generic_name": "Methyldopa",
        "brand_name": "Aldomet",
        "dosage_form": "Tablet",
        "strength": "250mg",
        "category": "Antihypertensive (Gestational)",
        "therapeutic_class": "Centrally Acting Alpha-2 Adrenergic Agonist",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "250mg PO 8-hourly (TDS), increasing up to 500mg TDS for gestational BP control",
        "is_cold_chain": False,
        "linked_icd10_codes": "O13.9,O14.9,I10",
        "nafdac_fda_number": "FDA/SD.24-0164",
        "description": "First-line safety profile antihypertensive for chronic and gestational hypertension in pregnancy.",
    },
    {
        "generic_name": "Spironolactone",
        "brand_name": "Aldactone",
        "dosage_form": "Tablet",
        "strength": "25mg",
        "category": "Potassium-Sparing Diuretic",
        "therapeutic_class": "Aldosterone Antagonist / MRA",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "25mg to 50mg PO once daily with serum potassium monitoring",
        "is_cold_chain": False,
        "linked_icd10_codes": "I50.9,K74.6,I10",
        "nafdac_fda_number": "FDA/SD.24-0165",
        "description": "Mineralocorticoid receptor antagonist for severe heart failure (NYHA III/IV) and hepatic ascites.",
    },
    {
        "generic_name": "Nifedipine Retard",
        "brand_name": "Adalat Retard",
        "dosage_form": "Extended Release Tablet",
        "strength": "20mg",
        "category": "Antihypertensive & Tocolytic",
        "therapeutic_class": "Calcium Channel Blocker",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "20mg PO 12-hourly (BD) or 20mg stat as acute tocolytic in preterm labor",
        "is_cold_chain": False,
        "linked_icd10_codes": "I10,O60.0",
        "nafdac_fda_number": "FDA/SD.24-0166",
        "description": "Sustained release CCB for hypertension and obstetric tocolysis in threatened preterm labor.",
    },

    # --------------------------------------------------------------------------
    # 4. ANALGESICS & ACT 857 CONTROLLED POISONS & NARCOTICS
    # --------------------------------------------------------------------------
    {
        "generic_name": "Paracetamol (Acetaminophen)",
        "brand_name": "Panadol / Para-Denk",
        "dosage_form": "Tablet",
        "strength": "500mg",
        "category": "Analgesic & Antipyretic",
        "therapeutic_class": "Non-Opioid Analgesic",
        "poison_schedule": "OTC",
        "standard_dosing": "1g (2 tablets) PO 6 to 8-hourly PRN (Max 4g/24h)",
        "is_cold_chain": False,
        "linked_icd10_codes": "R50.9,R51,R52",
        "nafdac_fda_number": "FDA/SD.24-0089",
        "description": "First-line non-opioid pain relief and antipyretic for primary outpatient and ward care.",
    },
    {
        "generic_name": "Paracetamol IV Infusion",
        "brand_name": "Perfalgan / Para IV",
        "dosage_form": "IV Infusion",
        "strength": "1000mg/100ml",
        "category": "Analgesic & Antipyretic",
        "therapeutic_class": "Non-Opioid Analgesic",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "1000mg IV infused over 15 minutes 6-hourly PRN",
        "is_cold_chain": False,
        "linked_icd10_codes": "R52,T88.9",
        "nafdac_fda_number": "FDA/SD.24-0090",
        "description": "Intravenous non-opioid analgesia for acute postoperative and trauma pain.",
    },
    {
        "generic_name": "Ibuprofen",
        "brand_name": "Brufen",
        "dosage_form": "Tablet",
        "strength": "400mg",
        "category": "NSAID",
        "therapeutic_class": "Non-Steroidal Anti-Inflammatory Drug",
        "poison_schedule": "OTC",
        "standard_dosing": "400mg PO 8-hourly with food (TDS) PRN",
        "is_cold_chain": False,
        "linked_icd10_codes": "M79.1,M25.5,N94.6",
        "nafdac_fda_number": "FDA/SD.24-0091",
        "description": "Non-steroidal anti-inflammatory for musculoskeletal pain, dysmenorrhea, and inflammatory arthritis.",
    },
    {
        "generic_name": "Diclofenac Sodium",
        "brand_name": "Voltaren",
        "dosage_form": "Tablet (Enteric Coated)",
        "strength": "50mg",
        "category": "NSAID",
        "therapeutic_class": "Acetic Acid Derivative NSAID",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "50mg PO 8-hourly or 75mg IM for acute renal colic / trauma",
        "is_cold_chain": False,
        "linked_icd10_codes": "N23,M54.5,M19.9",
        "nafdac_fda_number": "FDA/SD.24-0092",
        "description": "Potent anti-inflammatory for acute renal colic, post-traumatic soft tissue swelling, and osteoarthritis.",
    },
    {
        "generic_name": "Tramadol Hydrochloride",
        "brand_name": "Tramal / Tramadol",
        "dosage_form": "Capsule",
        "strength": "50mg",
        "category": "Moderate Opioid Analgesic",
        "therapeutic_class": "Synthetic Opioid / SNRI Agonist",
        "poison_schedule": "CLASS_B_POISON",
        "standard_dosing": "50mg to 100mg PO 6-hourly PRN (Max 400mg/24h) under Act 857 register",
        "is_cold_chain": False,
        "linked_icd10_codes": "R52,M54.5,T14.9",
        "nafdac_fda_number": "FDA/SD.24-0093",
        "description": "Controlled substance under Ghana Act 857 for moderate-to-severe surgical and chronic pain.",
    },
    {
        "generic_name": "Tramadol Hydrochloride Injection",
        "brand_name": "Tramal IV/IM",
        "dosage_form": "Injection",
        "strength": "100mg/2ml Ampoule",
        "category": "Moderate Opioid Analgesic",
        "therapeutic_class": "Synthetic Opioid",
        "poison_schedule": "CLASS_B_POISON",
        "standard_dosing": "100mg slow IV/IM 8-hourly with antiemetic co-prescription",
        "is_cold_chain": False,
        "linked_icd10_codes": "R52,T88.9",
        "nafdac_fda_number": "FDA/SD.24-0094",
        "description": "Parenteral controlled analgesic for acute emergency trauma and postoperative recovery.",
    },
    {
        "generic_name": "Morphine Sulphate",
        "brand_name": "Morphine Injection",
        "dosage_form": "Injection",
        "strength": "10mg/ml Ampoule",
        "category": "Strong Narcotic Analgesic",
        "therapeutic_class": "Pure Opioid Agonist (Schedule 1 / Act 857)",
        "poison_schedule": "CLASS_A_NARCOTIC",
        "standard_dosing": "5mg to 10mg SC/IM/slow IV 4-hourly with strict dangerous drugs register log",
        "is_cold_chain": False,
        "linked_icd10_codes": "C80.1,I21.9,T88.9",
        "nafdac_fda_number": "FDA/SD.24-0095",
        "description": "Class A Narcotic under Ghana Act 857 for terminal cancer pain and acute myocardial infarction.",
    },
    {
        "generic_name": "Pethidine Hydrochloride",
        "brand_name": "Pethidine Injection",
        "dosage_form": "Injection",
        "strength": "50mg/ml (2ml Ampoule)",
        "category": "Strong Narcotic Analgesic",
        "therapeutic_class": "Synthetic Phenylpiperidine Opioid",
        "poison_schedule": "CLASS_A_NARCOTIC",
        "standard_dosing": "50mg to 100mg IM 4-hourly during active stage labor or major surgery",
        "is_cold_chain": False,
        "linked_icd10_codes": "O80,R52",
        "nafdac_fda_number": "FDA/SD.24-0096",
        "description": "Class A Narcotic for intrapartum obstetric labor analgesia and acute perioperative pain.",
    },
    {
        "generic_name": "Diazepam",
        "brand_name": "Valium Injection",
        "dosage_form": "Injection",
        "strength": "10mg/2ml Ampoule",
        "category": "Anticonvulsant & Sedative",
        "therapeutic_class": "Benzodiazepine (Act 857 Controlled)",
        "poison_schedule": "CLASS_B_POISON",
        "standard_dosing": "10mg slow IV/rectal stat for status epilepticus and acute panic agitation",
        "is_cold_chain": False,
        "linked_icd10_codes": "G40.9,G41.9,F41.9",
        "nafdac_fda_number": "FDA/SD.24-0097",
        "description": "Emergency anticonvulsant for acute seizures, febrile convulsions, and muscle spasm relaxation.",
    },
    {
        "generic_name": "Codeine Phosphate",
        "brand_name": "Codeine Linctus / Tablets",
        "dosage_form": "Tablet",
        "strength": "30mg",
        "category": "Opioid Antitussive & Analgesic",
        "therapeutic_class": "Natural Opium Alkaloid (Act 857)",
        "poison_schedule": "CLASS_B_POISON",
        "standard_dosing": "30mg to 60mg PO 6-hourly PRN under strict pharmacist register",
        "is_cold_chain": False,
        "linked_icd10_codes": "R05,R52",
        "nafdac_fda_number": "FDA/SD.24-0098",
        "description": "Class B Poison under Act 857 for dry hacking cough and moderate somatic pain.",
    },

    # --------------------------------------------------------------------------
    # 5. COLD-CHAIN BIOLOGICS & VACCINES (2°C - 8°C STRICT REFRIGERATION)
    # --------------------------------------------------------------------------
    {
        "generic_name": "Human Insulin 70/30 (Biphasic Isophane)",
        "brand_name": "Mixtard 70/30 / Humulin 70/30",
        "dosage_form": "Suspension for Injection",
        "strength": "100 IU/ml (10ml Vial)",
        "category": "Cold-Chain Biologic",
        "therapeutic_class": "Recombinant Human Insulin",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "Individualized SC dosing 30 min before breakfast & dinner; store at 2°C-8°C",
        "is_cold_chain": True,
        "storage_temp_min": 2.0,
        "storage_temp_max": 8.0,
        "linked_icd10_codes": "E10.9,E11.9",
        "nafdac_fda_number": "FDA/SD.24-0301",
        "description": "Dual-action premixed human insulin for diabetes mellitus glycemic maintenance.",
    },
    {
        "generic_name": "Oxytocin",
        "brand_name": "Syntocinon / Pitocin",
        "dosage_form": "Injection",
        "strength": "10 IU/ml Ampoule",
        "category": "Cold-Chain Uterotonic",
        "therapeutic_class": "Synthetic Oxytocic Hormone",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "10 IU IM stat immediately after delivery of anterior shoulder for AMTSL; store at 2°C-8°C",
        "is_cold_chain": True,
        "storage_temp_min": 2.0,
        "storage_temp_max": 8.0,
        "linked_icd10_codes": "O72.1,O80",
        "nafdac_fda_number": "FDA/SD.24-0302",
        "description": "Critical cold-chain uterotonic for Active Management of Third Stage Labor (AMTSL) & PPH prevention.",
    },
    {
        "generic_name": "Anti-Rabies Vaccine (Purified Vero Cell)",
        "brand_name": "Verorab / Rabivax",
        "dosage_form": "Powder for Injection + Diluent",
        "strength": ">= 2.5 IU/Dose",
        "category": "Cold-Chain Vaccine",
        "therapeutic_class": "Inactivated Viral Vaccine",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "Post-exposure prophylaxis IM on Days 0, 3, 7, 14, and 28; store at 2°C-8°C",
        "is_cold_chain": True,
        "storage_temp_min": 2.0,
        "storage_temp_max": 8.0,
        "linked_icd10_codes": "A82.9,W54.0",
        "nafdac_fda_number": "FDA/SD.24-0303",
        "description": "Post-exposure rabies prophylaxis following suspected canine bites or lyssavirus exposure.",
    },
    {
        "generic_name": "Tetanus Toxoid Vaccine (Adsorbed)",
        "brand_name": "TT Vaccine",
        "dosage_form": "Suspension for Injection",
        "strength": "40 IU/0.5ml Ampoule",
        "category": "Cold-Chain Vaccine",
        "therapeutic_class": "Inactivated Bacterial Toxoid",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "0.5ml IM stat for trauma wound prophylaxis or ANC maternal immunization; store at 2°C-8°C",
        "is_cold_chain": True,
        "storage_temp_min": 2.0,
        "storage_temp_max": 8.0,
        "linked_icd10_codes": "A35,Z23,T14.1",
        "nafdac_fda_number": "FDA/SD.24-0304",
        "description": "Active immunization against Clostridium tetani for trauma wounds and maternal neonatal protection.",
    },
    {
        "generic_name": "Hepatitis B Vaccine (rDNA)",
        "brand_name": "Engerix-B / HepB",
        "dosage_form": "Suspension for Injection",
        "strength": "20mcg/ml (Adult) / 10mcg/0.5ml (Pediatric)",
        "category": "Cold-Chain Vaccine",
        "therapeutic_class": "Recombinant Viral Surface Antigen",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "IM doses at 0, 1, and 6 months for healthcare workers and birth dose neonates; store at 2°C-8°C",
        "is_cold_chain": True,
        "storage_temp_min": 2.0,
        "storage_temp_max": 8.0,
        "linked_icd10_codes": "B16.9,Z24.6",
        "nafdac_fda_number": "FDA/SD.24-0305",
        "description": "Essential recombinant vaccine for universal neonatal coverage and healthcare occupational protection.",
    },
    {
        "generic_name": "Polyvalent Snake Antivenom (African Viper/Elapid)",
        "brand_name": "Fav-Afrique / Inoserp",
        "dosage_form": "Liquid for IV Infusion",
        "strength": "10ml/Vial",
        "category": "Cold-Chain Antivenom",
        "therapeutic_class": "Equine Immunoglobulin F(ab')2 Fragments",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "2 to 4 vials diluted in 500ml Normal Saline infused IV over 1 hour; store at 2°C-8°C",
        "is_cold_chain": True,
        "storage_temp_min": 2.0,
        "storage_temp_max": 8.0,
        "linked_icd10_codes": "T63.0",
        "nafdac_fda_number": "FDA/SD.24-0306",
        "description": "Neutralizes venom of Echis ocellatus (carpet viper), Bitis arietans, and Naja nigricollis bites.",
    },

    # --------------------------------------------------------------------------
    # 6. MATERNAL, REPRODUCTIVE & CHILD HEALTH (MCH)
    # --------------------------------------------------------------------------
    {
        "generic_name": "Zinc Sulphate",
        "brand_name": "ZincKid / Zincol",
        "dosage_form": "Dispersible Tablet",
        "strength": "20mg",
        "category": "Essential Mineral",
        "therapeutic_class": "Nutritional Supplement / Antidiarrheal",
        "poison_schedule": "OTC",
        "standard_dosing": "20mg dissolved in breast milk/water once daily for 10-14 days for acute diarrhea in children",
        "is_cold_chain": False,
        "linked_icd10_codes": "A09,E60",
        "nafdac_fda_number": "FDA/SD.24-0255",
        "description": "WHO-recommended zinc supplementation reducing childhood diarrhea severity and recurrence.",
    },
    {
        "generic_name": "Oral Rehydration Salts (ORS)",
        "brand_name": "WHO Low-Osmolarity ORS",
        "dosage_form": "Sachet Powder",
        "strength": "20.5g/L Sachet",
        "category": "Electrolyte Solution",
        "therapeutic_class": "Oral Electrolyte Replacement",
        "poison_schedule": "OTC",
        "standard_dosing": "Dissolve 1 sachet in 1 liter clean drinking water; drink after each loose stool",
        "is_cold_chain": False,
        "linked_icd10_codes": "A09,E86.0",
        "nafdac_fda_number": "FDA/SD.24-0199",
        "description": "Life-saving low-osmolarity oral rehydration for diarrheal dehydration across all age groups.",
    },
    {
        "generic_name": "Folic Acid",
        "brand_name": "Folic Acid Tablets",
        "dosage_form": "Tablet",
        "strength": "5mg",
        "category": "Essential Vitamin",
        "therapeutic_class": "Vitamin B9 Supplement",
        "poison_schedule": "OTC",
        "standard_dosing": "5mg PO once daily throughout pregnancy and preconception",
        "is_cold_chain": False,
        "linked_icd10_codes": "D52.9,Z34.8",
        "nafdac_fda_number": "FDA/SD.24-0256",
        "description": "Neural tube defect prevention and megaloblastic anemia prophylaxis in antenatal care.",
    },
    {
        "generic_name": "Ferrous Sulphate",
        "brand_name": "Iron Tablets",
        "dosage_form": "Tablet",
        "strength": "200mg (65mg Elemental Iron)",
        "category": "Essential Mineral",
        "therapeutic_class": "Hematinic Iron Preparation",
        "poison_schedule": "OTC",
        "standard_dosing": "200mg PO 8-hourly with vitamin C or orange juice for iron deficiency anemia",
        "is_cold_chain": False,
        "linked_icd10_codes": "D50.9,Z34.8",
        "nafdac_fda_number": "FDA/SD.24-0257",
        "description": "First-line oral hematinic for nutritional iron deficiency and routine antenatal supplementation.",
    },
    {
        "generic_name": "Ergometrine Maleate",
        "brand_name": "Ergometrine Injection",
        "dosage_form": "Injection",
        "strength": "500mcg/ml Ampoule",
        "category": "Uterotonic",
        "therapeutic_class": "Ergot Alkaloid",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "500mcg IM stat for post-partum hemorrhage control (Contraindicated in hypertension)",
        "is_cold_chain": False,
        "linked_icd10_codes": "O72.1",
        "nafdac_fda_number": "FDA/SD.24-0258",
        "description": "Uterine smooth muscle contractor for severe atonic postpartum hemorrhage.",
    },
    {
        "generic_name": "Misoprostol",
        "brand_name": "Cytotec / Misofem",
        "dosage_form": "Tablet",
        "strength": "200mcg",
        "category": "Prostaglandin Analogue",
        "therapeutic_class": "Synthetic Prostaglandin E1",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "800mcg sublingually for incomplete abortion evacuation or 600mcg PO for PPH prevention",
        "is_cold_chain": False,
        "linked_icd10_codes": "O03.9,O72.1",
        "nafdac_fda_number": "FDA/SD.24-0259",
        "description": "Heat-stable uterotonic alternative for PPH prevention and medical management of incomplete abortion.",
    },
    {
        "generic_name": "Magnesium Sulphate",
        "brand_name": "Magnesium Sulphate 50%",
        "dosage_form": "Injection",
        "strength": "50% w/v (5g/10ml Ampoule)",
        "category": "Anticonvulsant (Obstetric)",
        "therapeutic_class": "Eclampsia Neuroprotective Anticonvulsant",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "Loading dose 4g IV + 10g deep IM (Pritchard Regimen), then 5g IM 4-hourly",
        "is_cold_chain": False,
        "linked_icd10_codes": "O14.1,O15.0",
        "nafdac_fda_number": "FDA/SD.24-0260",
        "description": "Gold-standard anticonvulsant for prevention and control of seizures in severe pre-eclampsia and eclampsia.",
    },
    {
        "generic_name": "Albendazole",
        "brand_name": "Zentel / Alben",
        "dosage_form": "Chewable Tablet",
        "strength": "400mg",
        "category": "Anthelmintic",
        "therapeutic_class": "Benzimidazole Anthelmintic",
        "poison_schedule": "OTC",
        "standard_dosing": "400mg chewable tablet stat as single dose; repeat in 2 weeks for enterobiasis",
        "is_cold_chain": False,
        "linked_icd10_codes": "B77.9,B76.9,B68.9",
        "nafdac_fda_number": "FDA/SD.24-0261",
        "description": "Mass deworming anthelmintic for ascariasis, hookworm, trichuriasis, and hydatid disease.",
    },

    # --------------------------------------------------------------------------
    # 7. RESPIRATORY, GASTROINTESTINAL & ENDOCRINE
    # --------------------------------------------------------------------------
    {
        "generic_name": "Salbutamol (Albuterol)",
        "brand_name": "Ventolin Inhaler",
        "dosage_form": "Metered Dose Inhaler",
        "strength": "100mcg/puff (200 Doses)",
        "category": "Bronchodilator (SABA)",
        "therapeutic_class": "Short-Acting Beta-2 Receptor Agonist",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "1 to 2 puffs inhaled 4-hourly PRN for acute bronchospasm / asthma attack",
        "is_cold_chain": False,
        "linked_icd10_codes": "J45.9,J44.9",
        "nafdac_fda_number": "FDA/SD.24-0280",
        "description": "Rapid rescue bronchodilator for acute asthma exacerbation and COPD bronchospasm.",
    },
    {
        "generic_name": "Beclomethasone Dipropionate",
        "brand_name": "Becotide Inhaler",
        "dosage_form": "Metered Dose Inhaler",
        "strength": "100mcg/puff",
        "category": "Inhaled Corticosteroid",
        "therapeutic_class": "Inhaled Anti-Inflammatory Steroid",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "2 puffs inhaled 12-hourly (BD) regular maintenance; rinse mouth after use",
        "is_cold_chain": False,
        "linked_icd10_codes": "J45.9",
        "nafdac_fda_number": "FDA/SD.24-0281",
        "description": "First-line inhaled corticosteroid controller for persistent chronic bronchial asthma.",
    },
    {
        "generic_name": "Omeprazole",
        "brand_name": "Losec / Ocid",
        "dosage_form": "Capsule (Enteric Coated)",
        "strength": "20mg",
        "category": "Proton Pump Inhibitor (PPI)",
        "therapeutic_class": "Gastric Acid Pump Inhibitor",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "20mg PO once daily 30 min before breakfast for 4 to 8 weeks",
        "is_cold_chain": False,
        "linked_icd10_codes": "K25.9,K27.9,K21.9",
        "nafdac_fda_number": "FDA/SD.24-0178",
        "description": "Suppresses gastric parietal acid secretion for peptic ulcer disease and severe gastroesophageal reflux.",
    },
    {
        "generic_name": "Magnesium Trisilicate Compound",
        "brand_name": "MMT Oral Suspension",
        "dosage_form": "Oral Suspension",
        "strength": "200ml Bottle",
        "category": "Antacid",
        "therapeutic_class": "Antacid / Mucosal Protectant",
        "poison_schedule": "OTC",
        "standard_dosing": "10ml to 20ml PO 3 times daily between meals and at bedtime",
        "is_cold_chain": False,
        "linked_icd10_codes": "K29.7,K30",
        "nafdac_fda_number": "FDA/SD.24-0179",
        "description": "Fast-acting neutralizing suspension for dyspepsia, heartburn, and acute gastritis symptoms.",
    },
    {
        "generic_name": "Promethazine Hydrochloride",
        "brand_name": "Phenergan",
        "dosage_form": "Tablet",
        "strength": "25mg",
        "category": "Antihistamine & Antiemetic",
        "therapeutic_class": "First-Generation H1 Antagonist / Phenothiazine",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "25mg PO at night for allergy or 25mg 8-hourly for acute motion sickness / nausea",
        "is_cold_chain": False,
        "linked_icd10_codes": "R11.0,T78.4",
        "nafdac_fda_number": "FDA/SD.24-0180",
        "description": "Sedating antihistamine and antiemetic for severe nausea, urticaria, and pre-medication sedation.",
    },
    {
        "generic_name": "Cetirizine Hydrochloride",
        "brand_name": "Zyrtec / Cetriz",
        "dosage_form": "Tablet",
        "strength": "10mg",
        "category": "Antihistamine",
        "therapeutic_class": "Second-Generation Non-Sedating H1 Antagonist",
        "poison_schedule": "OTC",
        "standard_dosing": "10mg PO once daily (OD)",
        "is_cold_chain": False,
        "linked_icd10_codes": "J30.9,L50.9",
        "nafdac_fda_number": "FDA/SD.24-0181",
        "description": "Non-sedating antihistamine for allergic rhinitis, allergic conjunctivitis, and chronic urticaria.",
    },
    {
        "generic_name": "Prednisolone",
        "brand_name": "Prednisolone Tablets",
        "dosage_form": "Tablet",
        "strength": "5mg",
        "category": "Systemic Corticosteroid",
        "therapeutic_class": "Glucocorticoid Anti-Inflammatory",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "20mg to 40mg PO morning dose, tapering gradually under clinical supervision",
        "is_cold_chain": False,
        "linked_icd10_codes": "J45.9,M06.9,L20.9",
        "nafdac_fda_number": "FDA/SD.24-0182",
        "description": "Systemic glucocorticoid for severe acute asthma exacerbations, nephrotic syndrome, and autoimmune disease.",
    },
    {
        "generic_name": "Hydrocortisone Sodium Succinate",
        "brand_name": "Solu-Cortef IV",
        "dosage_form": "Powder for Injection",
        "strength": "100mg/Vial",
        "category": "Emergency Corticosteroid",
        "therapeutic_class": "Emergency Glucocorticoid",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "100mg to 200mg slow IV stat for anaphylactic shock and acute Addisonian crisis",
        "is_cold_chain": False,
        "linked_icd10_codes": "T78.2,E27.2",
        "nafdac_fda_number": "FDA/SD.24-0183",
        "description": "Emergency life-saving intravenous steroid for anaphylaxis, severe angioedema, and adrenal crisis.",
    },

    # --------------------------------------------------------------------------
    # 8. TOPICAL, OPHTHALMIC & ANTISEPTIC PREPARATIONS
    # --------------------------------------------------------------------------
    {
        "generic_name": "Chloramphenicol Eye Drops",
        "brand_name": "Chloramphenicol 0.5%",
        "dosage_form": "Eye Drops",
        "strength": "0.5% (10ml Bottle)",
        "category": "Ophthalmic Antibiotic",
        "therapeutic_class": "Broad-Spectrum Ophthalmic Antimicrobial",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "1 to 2 drops into affected eye(s) 2 to 4-hourly for 5 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "H10.9",
        "nafdac_fda_number": "FDA/SD.24-0350",
        "description": "First-line topical antimicrobial for acute bacterial conjunctivitis and corneal abrasions.",
    },
    {
        "generic_name": "Ciprofloxacin Eye/Ear Drops",
        "brand_name": "Ciloxan / Cipro Drops",
        "dosage_form": "Eye/Ear Drops",
        "strength": "0.3% (5ml Bottle)",
        "category": "Ophthalmic/Otic Antibiotic",
        "therapeutic_class": "Fluoroquinolone Topical",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "1 to 2 drops in eye or 4 drops in ear canal 8-hourly for 7 days",
        "is_cold_chain": False,
        "linked_icd10_codes": "H16.0,H60.9",
        "nafdac_fda_number": "FDA/SD.24-0351",
        "description": "Indicated for severe corneal ulcers, Pseudomonas otitis externa, and suppurative otitis media.",
    },
    {
        "generic_name": "Clotrimazole Cream",
        "brand_name": "Canesten Cream",
        "dosage_form": "Topical Cream",
        "strength": "1% (20g Tube)",
        "category": "Topical Antifungal",
        "therapeutic_class": "Imidazole Antifungal",
        "poison_schedule": "OTC",
        "standard_dosing": "Apply thinly to affected cutaneous area 2 to 3 times daily for 2 to 4 weeks",
        "is_cold_chain": False,
        "linked_icd10_codes": "B35.9,B36.0",
        "nafdac_fda_number": "FDA/SD.24-0352",
        "description": "Topical antifungal for tinea pedis (athlete foot), tinea corporis, and cutaneous candidiasis.",
    },
    {
        "generic_name": "Silver Sulfadiazine",
        "brand_name": "Flamazine Cream",
        "dosage_form": "Topical Cream",
        "strength": "1% (50g Jar)",
        "category": "Burn Wound Chemotherapeutic",
        "therapeutic_class": "Topical Sulfonamide Antimicrobial",
        "poison_schedule": "PRESCRIPTION_ONLY",
        "standard_dosing": "Apply 2-3mm sterile layer over cleaned burn wound once or twice daily with dressing",
        "is_cold_chain": False,
        "linked_icd10_codes": "T30.0,L08.9",
        "nafdac_fda_number": "FDA/SD.24-0353",
        "description": "Broad-spectrum antibacterial cream for prevention and treatment of sepsis in 2nd/3rd degree burns.",
    },
]


async def seed_essential_formulary(session: AsyncSession) -> int:
    """
    Seeds and idempotently updates the statutory WHO & Ghana FDA essential
    medicines formulary into the GlobalMedication registry.
    """
    count = 0
    for med in GHANA_FDA_WHO_ESSENTIAL_FORMULARY:
        if med.get("nafdac_fda_number"):
            stmt = select(GlobalMedication).where(
                or_(
                    GlobalMedication.nafdac_fda_number == med["nafdac_fda_number"],
                    (GlobalMedication.generic_name == med["generic_name"]) &
                    (GlobalMedication.strength == med["strength"])
                )
            )
        else:
            stmt = select(GlobalMedication).where(
                (GlobalMedication.generic_name == med["generic_name"]) &
                (GlobalMedication.strength == med["strength"])
            )
        res = await session.execute(stmt)
        existing = res.scalars().first()

        if not existing:
            global_med = GlobalMedication(
                id=uuid.uuid4(),
                generic_name=med["generic_name"],
                brand_name=med["brand_name"],
                dosage_form=med["dosage_form"],
                strength=med["strength"],
                category=med["category"],
                therapeutic_class=med.get("therapeutic_class"),
                poison_schedule=med.get("poison_schedule", "OTC"),
                standard_dosing=med.get("standard_dosing"),
                is_cold_chain=med.get("is_cold_chain", False),
                storage_temp_min=med.get("storage_temp_min"),
                storage_temp_max=med.get("storage_temp_max"),
                linked_icd10_codes=med.get("linked_icd10_codes"),
                nafdac_fda_number=med.get("nafdac_fda_number"),
                description=med.get("description"),
            )
            session.add(global_med)
            count += 1
        else:
            # Update statutory clinical metadata
            existing.generic_name = med["generic_name"]
            existing.brand_name = med["brand_name"]
            existing.dosage_form = med["dosage_form"]
            existing.strength = med["strength"]
            existing.category = med["category"]
            existing.therapeutic_class = med.get("therapeutic_class")
            existing.poison_schedule = med.get("poison_schedule", "OTC")
            existing.standard_dosing = med.get("standard_dosing")
            existing.is_cold_chain = med.get("is_cold_chain", False)
            existing.storage_temp_min = med.get("storage_temp_min")
            existing.storage_temp_max = med.get("storage_temp_max")
            existing.linked_icd10_codes = med.get("linked_icd10_codes")
            existing.nafdac_fda_number = med.get("nafdac_fda_number")
            existing.description = med.get("description")

    await session.flush()
    logger.info(f"[+] Processed {len(GHANA_FDA_WHO_ESSENTIAL_FORMULARY)} statutory formulary medicines (added {count} new)")
    return count

